"""initial migration

Revision ID: 479d26f71dd3
Revises: None
Create Date: 2017-05-14 21:50:30.084551

"""

# revision identifiers, used by Alembic.
revision = '479d26f71dd3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icao_type', sa.String(length=40), nullable=True),
    sa.Column('registration', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Integer(), nullable=True),
    sa.Column('track', sa.Integer(), nullable=True),
    sa.Column('ground_speed', sa.Integer(), nullable=True),
    sa.Column('air_speed', sa.Integer(), nullable=True),
    sa.Column('vertical_speed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], [u'aircraft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position')
    op.drop_table('aircraft')
    # ### end Alembic commands ###
