"""add aircraft description

Revision ID: 5de9e9fcdf6f
Revises: 479d26f71dd3
Create Date: 2017-05-15 23:55:55.702238

"""

# revision identifiers, used by Alembic.
revision = '5de9e9fcdf6f'
down_revision = '479d26f71dd3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aircraft', sa.Column('description', sa.String(length=260), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aircraft', 'description')
    # ### end Alembic commands ###
